### ISSUE TITLE
need help with scratchcozmosdk

### ISSUE THREAD

**Issue by cozmoplay** [madfrog54321/ScratchCozmoSDK#6]
great work in integrating cozmo with scratch!

need help in getting this a go...

I get a red bubble, missing cozmo controller app.
do I need to load an extension?

After I connect to the Cozmo SDK and run the cozmo controller app on python, the scratchx environment is loaded but no action is being performed.

**Comment by madfrog54321** [comment]
Please run the app to the point where scratchx is opened. Then open your [browser's Javascript console]( https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers). Post the error here. Also post the output of the python app. Additionally, what os and web browser are you using?

**Comment by cozmoplay** [comment]
ios10, internet explorer

I get an message on scratchx -
" see the tips window to install the plug in and get the extension working

python 
== Cozmo Controller v0.2.8 ===
[Server] Starting server...
[Server] Server ready at: localhost:9090
[Server] Websockets ready at: localhost:9090/ws
[Server] Web browser openned to: http://localhost:9090
[Server] Connected to web app
[Robot] Connected to Cozmo!

Console
websocket err
![scratchx](https://user-images.githubusercontent.com/30572315/28924938-fc62678c-7828-11e7-819b-63614fbc0d8e.JPG)

**Comment by madfrog54321** [comment]
Thank you. IE and Edge block websites connecting to localhost by default. You can try following https://github.com/qzind/qz-print/issues/39 to remove the restriction. Also chrome and Firefox don't block the app.

**Comment by cozmoplay** [comment]
Thank you very much! It works great!
